title: 零星笔记
description: My Personal Stack Problems
author: 山沟沟
github: https://github.com/agusmakmun
about: 这是放个人简介的地方.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

# social:
#     - icon: fa-facebook
#       link: "#"
#     - icon: fa-skype
#       link: "#"
#     - icon: fa-twitter
#       link: "https://twitter.com/agusmakmun6"
#     - icon: fa-linkedin
#       link: "#"
#     - icon: fa-stack-exchange
#       link: "#"

# share:
#   twitter_username: agusmakmun6
#   fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    # - text: Projects
    #   url: /projects/
    # - text: Github
    #   url: https://github.com/agusmakmun
    - text: XML Feed
      url: /feed.xml

url: "https://linsir123.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist